# Generated by Django 4.2.15 on 2024-08-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="faces/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("recognized", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RecognizedFace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "face_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognized_faces",
                        to="face_recog_app.faceimage",
                    ),
                ),
            ],
        ),
    ]
