# Generated by Django 4.2.15 on 2024-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("prediction", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
